<?php


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\ReportController as AdminReportController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Kasir\DashboardController as KasirDashboardController;
use App\Http\Controllers\Kasir\TransactionController;
use App\Http\Controllers\Kasir\ReportController as KasirReportController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\MidtransCallbackController;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\ProfileController;


Route::get('/', function () {
    if (Auth::check()) {
        $user = Auth::user();

        if ($user->role === 'admin') {
            return redirect()->route('admin.dashboard');
        }

        if ($user->role === 'kasir') {
            return redirect()->route('kasir.dashboard');
        }
    }

    return view('auth.login');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});





// Authentication routes (generated by Breeze)
Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])
        ->name('login');
    // ... other auth routes
});

// Admin routes
Route::middleware(['auth', 'admin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', [AdminDashboardController::class, 'index'])->name('dashboard');

    // Menu management
    Route::get('/menu', [MenuController::class, 'index'])->name('menu.index');
    Route::get('/menu/create', [MenuController::class, 'create'])->name('menu.create');
    Route::post('/menu', [MenuController::class, 'store'])->name('menu.store');
    Route::get('/menu/{menu}/edit', [MenuController::class, 'edit'])->name('menu.edit');
    Route::put('/menu/{menu}', [MenuController::class, 'update'])->name('menu.update');
    Route::delete('/menu/{menu}', [MenuController::class, 'destroy'])->name('menu.destroy');

    // Reports
    Route::get('/reports', [AdminReportController::class, 'index'])->name('reports');

    // User management
    Route::resource('users', UserController::class);
});

// Kasir routes
Route::middleware(['auth', 'kasir'])->prefix('kasir')->name('kasir.')->group(function () {
    Route::get('/dashboard', [KasirDashboardController::class, 'index'])->name('dashboard');

    // Transaction
    Route::get('/transaction', [TransactionController::class, 'create'])->name('transaction.create');
    Route::post('/transaction', [TransactionController::class, 'store'])->name('transaction.store');
    Route::post('/transaction/{transaction}/payment-status', [TransactionController::class, 'updatePaymentStatus'])->name('transaction.payment-status');
    Route::get('/transaction/{transaction}/receipt', [TransactionController::class, 'receipt'])->name('transaction.receipt');
    // Reports
    Route::get('/reports', [KasirReportController::class, 'index'])->name('reports');
    Route::get('/reports/transaction/{transaction}', [KasirReportController::class, 'show'])->name('reports.transaction.show');
    Route::get('/reports/export', [KasirReportController::class, 'export'])->name('reports.export');
    Route::get('/reports/receipt/{transaction}', [KasirReportController::class, 'receipt'])->name('reports.receipt');
    Route::get('/reports/today-print', [KasirReportController::class, 'todayReport'])->name('reports.today-print');
});

Route::post('/midtrans/notification', MidtransCallbackController::class)->name('midtrans.notification');

// Redirect based on role after login
// Route::get('/redirect', function () {

//     /** @var User $user */
//     $user = Auth::user();

//     if ($user->isAdmin()) {
//         return redirect()->route('admin.dashboard');
//     }

//     return redirect()->route('kasir.dashboard');
// })->middleware('auth')->name('redirect');

require __DIR__ . '/auth.php';
